### ISSUE TITLE
[Feature Request] Inches not Centimeters

### ISSUE THREAD

**Issue by karmanyaahm** [Poetic1843/vrc-map#10]
It would be great if the distances this shows are in inches rather than cm. I personally also think metric is superior, but the rules and field elements are in inches, so it makes my brain have to put in more effort.

It's a very nice tool btw.

**Comment by iseau395** [comment]
I'll make a toggle for cm or inches

**Comment by iseau395** [comment]
Also thanks!

**Comment by iseau395** [comment]
Added with commit [aef7166](https://github.com/Poetic1843/vrc-map/commit/aef7166c02f61a91305b7a0245db9d72ac7c6502)
